//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Me.Common {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Me.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; BEGIN mode {0}.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console mode.
        /// </summary>
        public static string ConsoleMode {
            get {
                return ResourceManager.GetString("ConsoleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting file {0}.
        /// </summary>
        public static string DeletingFile {
            get {
                return ResourceManager.GetString("DeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting folder {0}.
        /// </summary>
        public static string DeletingFolder {
            get {
                return ResourceManager.GetString("DeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; END mode {0} : Exitcode={1}.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing FTPSync process.
        /// </summary>
        public static string ExecFtpSync {
            get {
                return ResourceManager.GetString("ExecFtpSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FTPSync.exe folder= {0}.
        /// </summary>
        public static string ExeFolderName {
            get {
                return ResourceManager.GetString("ExeFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path to FTPSync.exe file= {0}.
        /// </summary>
        public static string ExePath {
            get {
                return ResourceManager.GetString("ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File &quot;{0}&quot; was not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found a serie {0} file= {1}.
        /// </summary>
        public static string FoundMovie {
            get {
                return ResourceManager.GetString("FoundMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FTPSync directly..
        /// </summary>
        public static string FTPSync {
            get {
                return ResourceManager.GetString("FTPSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à synchronization was successful.
        /// </summary>
        public static string FTPSyncError_0 {
            get {
                return ResourceManager.GetString("FTPSyncError_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à could not connect to FTP server (either source or destination).
        /// </summary>
        public static string FTPSyncError_1 {
            get {
                return ResourceManager.GetString("FTPSyncError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à error during copy (some files where probably copied, but not all; or aborted by user).
        /// </summary>
        public static string FTPSyncError_2 {
            get {
                return ResourceManager.GetString("FTPSyncError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à error during directory parsing (connection was successful, but FTPSync was unable to read source directory and build file index; no copying has been done).
        /// </summary>
        public static string FTPSyncError_3 {
            get {
                return ResourceManager.GetString("FTPSyncError_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à initialization error (most likely, something is wrong in the .INI file).
        /// </summary>
        public static string FTPSyncError_4 {
            get {
                return ResourceManager.GetString("FTPSyncError_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undefined error.
        /// </summary>
        public static string FTPSyncError_Undefined {
            get {
                return ResourceManager.GetString("FTPSyncError_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ended FtpSync process with Exitcode: {0}.
        /// </summary>
        public static string FTPSyncExitCode {
            get {
                return ResourceManager.GetString("FTPSyncExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting downloaded files list.
        /// </summary>
        public static string GetDownloadedList {
            get {
                return ResourceManager.GetString("GetDownloadedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting FTPSync exe folder.
        /// </summary>
        public static string GetExeFolder {
            get {
                return ResourceManager.GetString("GetExeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting FTPSync.exe path.
        /// </summary>
        public static string GetExePath {
            get {
                return ResourceManager.GetString("GetExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting ini fileName.
        /// </summary>
        public static string GetIni {
            get {
                return ResourceManager.GetString("GetIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting series files list.
        /// </summary>
        public static string GetSeriesList {
            get {
                return ResourceManager.GetString("GetSeriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting series name.
        /// </summary>
        public static string GetSeriesName {
            get {
                return ResourceManager.GetString("GetSeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gui exitcode: {0}.
        /// </summary>
        public static string GuiExitCode {
            get {
                return ResourceManager.GetString("GuiExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MeFTPSyncHelper GUI mode..
        /// </summary>
        public static string GUIMode {
            get {
                return ResourceManager.GetString("GUIMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ini file name= {0}.
        /// </summary>
        public static string IniName {
            get {
                return ResourceManager.GetString("IniName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moving file {0} to {1}.
        /// </summary>
        public static string MovingFile {
            get {
                return ResourceManager.GetString("MovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: A new file {1} were added in {2} serie !.
        /// </summary>
        public static string NewMovieAdded {
            get {
                return ResourceManager.GetString("NewMovieAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No file was downloaded today !.
        /// </summary>
        public static string NoDownload {
            get {
                return ResourceManager.GetString("NoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: No file was found in series !.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parsing FTPSync.exe error in event handler.
        /// </summary>
        public static string Parsing {
            get {
                return ResourceManager.GetString("Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application is running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start FtpSync process with arguments: {0}.
        /// </summary>
        public static string StartFtpSync {
            get {
                return ResourceManager.GetString("StartFtpSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storing downloaded files.
        /// </summary>
        public static string Storing {
            get {
                return ResourceManager.GetString("Storing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage: {0}.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prints version information to standard output..
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
